using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using WorkForce360.Api.Data;using WorkForce360.Api.Models;using WorkForce360.Api.Services;
namespace WorkForce360.Api.Controllers;
[ApiController,Route("api/trip-requests"),Authorize]
public class TripRequestsController(TripDbContext db,TripPlanningRules rules):ControllerBase
{
 public record TripDto(string Objective,DateOnly StartDate,DateOnly EndDate,int Pax,decimal BudgetUsd,string? Preferences);
 [HttpGet]public async Task<IActionResult> Get(string? status,string? search,int page=1,int pageSize=20){var q=db.TripRequests.AsNoTracking().Include(x=>x.Tourist).ThenInclude(x=>x.User).Where(x=>!x.IsDeleted);if(User.IsInRole("Tourist")){var uid=UserId();q=q.Where(x=>x.Tourist.UserId==uid);}if(Enum.TryParse<TripStatus>(status,true,out var s))q=q.Where(x=>x.Status==s);if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.Objective.ToLower().Contains(search.ToLower())||x.Tourist.User.FullName.ToLower().Contains(search.ToLower()));var total=await q.CountAsync();var items=await q.OrderByDescending(x=>x.CreatedAt).Skip((Math.Max(page,1)-1)*Math.Clamp(pageSize,1,100)).Take(Math.Clamp(pageSize,1,100)).Select(x=>new{x.Id,tourist=x.Tourist.User.FullName,x.Objective,x.StartDate,x.EndDate,x.Pax,x.BudgetUsd,status=x.Status.ToString(),x.CreatedAt}).ToListAsync();return Ok(new{items,totalCount=total,page,pageSize,totalPages=(int)Math.Ceiling(total/(double)pageSize)});}
 [HttpGet("{id:guid}")]public async Task<IActionResult> One(Guid id){var q=db.TripRequests.AsNoTracking().Include(x=>x.Tourist).ThenInclude(x=>x.User).Include(x=>x.Itinerary).ThenInclude(x=>x!.Days).ThenInclude(x=>x.Stops).ThenInclude(x=>x.Attraction).Include(x=>x.Quotations).ThenInclude(x=>x.Lines).Where(x=>x.Id==id);if(User.IsInRole("Tourist"))q=q.Where(x=>x.Tourist.UserId==UserId());var x=await q.SingleOrDefaultAsync();return x is null?NotFound():Ok(x);}
 [HttpPost,Authorize(Roles="Tourist")]public async Task<IActionResult> Create(TripDto r){var errors=rules.Validate(r.StartDate,r.EndDate,r.Pax,r.BudgetUsd,r.Objective);if(errors.Count>0)return ValidationProblem(new ValidationProblemDetails(new Dictionary<string,string[]>{{"trip",errors.ToArray()}}));var tourist=await db.Tourists.SingleOrDefaultAsync(x=>x.UserId==UserId());if(tourist is null)return BadRequest();var trip=new TripRequest{TouristId=tourist.Id,Objective=r.Objective.Trim(),StartDate=r.StartDate,EndDate=r.EndDate,Pax=r.Pax,BudgetUsd=r.BudgetUsd,PreferencesJson=r.Preferences??"{}"};db.Add(trip);await db.SaveChangesAsync();return Created($"/api/trip-requests/{trip.Id}",trip);}
 [HttpPost("{id:guid}/start-planning"),Authorize(Roles="OperationsManager")]public async Task<IActionResult> Plan(Guid id){var trip=await db.TripRequests.FindAsync(id);if(trip is null)return NotFound();if(trip.Status!=TripStatus.Submitted&&trip.Status!=TripStatus.RevisionRequested)return Conflict();trip.Status=TripStatus.PendingApproval;var itinerary=new Itinerary{TripRequestId=id,GeneratedBy="Planning service pending"};foreach(var day in rules.BuildSkeleton(trip.StartDate,trip.EndDate))itinerary.Days.Add(day);db.Add(itinerary);var quote=new Quotation{TripRequestId=id,Status=QuoteStatus.PendingApproval,TotalUsd=0};db.Add(quote);await db.SaveChangesAsync();return Accepted(new{trip.Id,status=trip.Status.ToString(),message="Planning workflow boundary created; connect LangGraph service next."});}
 private Guid UserId()=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirstValue("sub")!);
}
