using System.ComponentModel.DataAnnotations;
namespace WorkForce360.Api.Models;

public abstract class TripEntity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime UpdatedAt { get; set; } = DateTime.UtcNow; public bool IsDeleted { get; set; } }
public enum TripRole { Tourist, Guide, OperationsManager, Admin }
public enum TripStatus { Submitted, Planning, PendingApproval, Approved, Rejected, RevisionRequested, Confirmed, InProgress, Completed, Cancelled }
public enum QuoteStatus { Draft, PendingApproval, Approved, Rejected, RevisionRequested, Accepted }
public enum HoldStatus { Held, Released }

public class TripUser : TripEntity { [MaxLength(160)] public string Email { get; set; }=""; [MaxLength(120)] public string FullName { get; set; }=""; public string PasswordHash { get; set; }=""; public TripRole Role { get; set; }=TripRole.Tourist; public bool IsActive { get; set; }=true; public string? RefreshTokenHash { get; set; } public DateTime? RefreshTokenExpiresAt { get; set; } public Tourist? Tourist { get; set; } public Guide? Guide { get; set; } }
public class Tourist : TripEntity { public Guid UserId { get; set; } public TripUser User { get; set; }=null!; [MaxLength(80)] public string? Nationality { get; set; } [MaxLength(8)] public string? PassportNumberMasked { get; set; } public string? PassportPhotoUrl { get; set; } }
public class TripRequest : TripEntity { public Guid TouristId { get; set; } public Tourist Tourist { get; set; }=null!; [MaxLength(2000)] public string Objective { get; set; }=""; public DateOnly StartDate { get; set; } public DateOnly EndDate { get; set; } public int Pax { get; set; } public decimal BudgetUsd { get; set; } public string PreferencesJson { get; set; }="{}"; public TripStatus Status { get; set; }=TripStatus.Submitted; public Itinerary? Itinerary { get; set; } public ICollection<Quotation> Quotations { get; set; }=[]; }
public class Attraction : TripEntity { [MaxLength(140)] public string Name { get; set; }=""; [MaxLength(80)] public string City { get; set; }=""; [MaxLength(80)] public string Category { get; set; }=""; public int DurationMinutes { get; set; } public decimal EntryFeeLkr { get; set; } public decimal Latitude { get; set; } public decimal Longitude { get; set; } }
public class Itinerary : TripEntity { public Guid TripRequestId { get; set; } public TripRequest TripRequest { get; set; }=null!; public int Version { get; set; }=1; [MaxLength(30)] public string GeneratedBy { get; set; }="Manual"; public ICollection<ItineraryDay> Days { get; set; }=[]; }
public class ItineraryDay : TripEntity { public Guid ItineraryId { get; set; } public Itinerary Itinerary { get; set; }=null!; public int DayNumber { get; set; } [MaxLength(80)] public string City { get; set; }=""; public Guid? HotelId { get; set; } public string? Notes { get; set; } public ICollection<ItineraryStop> Stops { get; set; }=[]; }
public class ItineraryStop : TripEntity { public Guid ItineraryDayId { get; set; } public Guid AttractionId { get; set; } public Attraction Attraction { get; set; }=null!; public int Sequence { get; set; } public TimeOnly? ArrivalTime { get; set; } }
public class Guide : TripEntity { public Guid? UserId { get; set; } public TripUser? User { get; set; } [MaxLength(120)] public string Name { get; set; }=""; public decimal DayRateLkr { get; set; } public int MaxPax { get; set; } public bool IsActive { get; set; }=true; [MaxLength(100)] public string Languages { get; set; }="English"; }
public class Vehicle : TripEntity { [MaxLength(30)] public string RegistrationNo { get; set; }=""; [MaxLength(60)] public string Type { get; set; }=""; public int Seats { get; set; } public decimal RatePerKmLkr { get; set; } public bool IsActive { get; set; }=true; }
public class Hotel : TripEntity { [MaxLength(140)] public string Name { get; set; }=""; [MaxLength(80)] public string City { get; set; }=""; public int StarRating { get; set; } public decimal Latitude { get; set; } public decimal Longitude { get; set; } public ICollection<RoomType> RoomTypes { get; set; }=[]; }
public class RoomType : TripEntity { public Guid HotelId { get; set; } public Hotel Hotel { get; set; }=null!; [MaxLength(80)] public string Name { get; set; }=""; public int Capacity { get; set; } public decimal RatePerNightLkr { get; set; } public int TotalRooms { get; set; } }
public class ResourceHold : TripEntity { [MaxLength(20)] public string ResourceType { get; set; }=""; public Guid ResourceId { get; set; } public Guid TripRequestId { get; set; } public DateOnly FromDate { get; set; } public DateOnly ToDate { get; set; } public int Quantity { get; set; }=1; public HoldStatus Status { get; set; }=HoldStatus.Held; }
public class Quotation : TripEntity { public Guid TripRequestId { get; set; } public TripRequest TripRequest { get; set; }=null!; public int Version { get; set; }=1; public decimal SubtotalLkr { get; set; } public decimal MarginPct { get; set; }=15; public decimal TotalLkr { get; set; } public decimal TotalUsd { get; set; } public decimal FxRate { get; set; }=300; public DateTime FxAsOf { get; set; }=DateTime.UtcNow; public QuoteStatus Status { get; set; }=QuoteStatus.Draft; public ICollection<QuotationLine> Lines { get; set; }=[]; }
public class QuotationLine : TripEntity { public Guid QuotationId { get; set; } [MaxLength(30)] public string LineType { get; set; }=""; [MaxLength(300)] public string Description { get; set; }=""; public decimal Qty { get; set; } public decimal UnitLkr { get; set; } public decimal AmountLkr { get; set; } }
public class ApprovalDecision : TripEntity { public Guid QuotationId { get; set; } public Guid DecidedBy { get; set; } [MaxLength(30)] public string Decision { get; set; }=""; public string? Comment { get; set; } public DateTime DecidedAt { get; set; }=DateTime.UtcNow; }
public class TripAuditLog : TripEntity { public Guid? ActorId { get; set; } public string Action { get; set; }=""; public string Entity { get; set; }=""; public Guid EntityId { get; set; } public string? BeforeJson { get; set; } public string? AfterJson { get; set; } public DateTime At { get; set; }=DateTime.UtcNow; }
