import{useMemo,useState}from'react'

const staff=[
 {name:'Maya Chen',role:'Product Designer',dept:'Product',status:'Active',initials:'MC'},
 {name:'Daniel Brooks',role:'Frontend Engineer',dept:'Engineering',status:'Active',initials:'DB'},
 {name:'Priya Nair',role:'People Operations',dept:'Human Resources',status:'On leave',initials:'PN'},
 {name:'Liam Wilson',role:'Sales Executive',dept:'Sales',status:'Active',initials:'LW'},
 {name:'Sofia Martins',role:'QA Engineer',dept:'Engineering',status:'Remote',initials:'SM'},
]
const nav=[['Dashboard','⌂'],['Employees','♙'],['Attendance','◷'],['Shifts','□'],['Leave','✈'],['Performance','⌁'],['AI Workflows','✦'],['Settings','⚙']]

function Sidebar({page,setPage,open,setOpen}){return <aside className={open?'open':''}><div className="brand"><b>W</b><strong>WorkForce<span>360</span></strong></div><small className="label">WORKSPACE</small><nav>{nav.map(([n,i])=><button className={page===n?'active':''} onClick={()=>{setPage(n);setOpen(false)}} key={n}><i>{i}</i>{n}{n==='Leave'&&<em>8</em>}</button>)}</nav><div className="help"><b>?</b><span><strong>Need some help?</strong><small>Visit our help center</small></span></div></aside>}
function Header({page,menu}){return <header><button className="hamb" onClick={menu}>☰</button><div><h1>{page}</h1><p>{page==='Dashboard'?"Here's what's happening with your team today.":`Manage your ${page.toLowerCase()} workspace.`}</p></div><div className="head-actions"><button>⌕</button><button className="bell">♢<i/></button><div className="me"><b>AR</b><span><strong>Alex Rivera</strong><small>HR Manager</small></span></div></div></header>}
function Stat({title,value,change,note,icon,color}){return <article className="stat"><i className={color}>{icon}</i><small>{title}</small><strong>{value}</strong><p className={change<0?'down':''}><b>{change>0?'↗':change<0?'↘':'•'} {Math.abs(change)}%</b> {note}</p></article>}
function Dashboard({go}){return <><div className="tools"><span>▣ &nbsp; Sep 21 – Sep 27, 2026</span><button className="primary" onClick={()=>go('Employees')}>＋ Add employee</button></div><section className="stats"><Stat title="TOTAL EMPLOYEES" value="248" change={8.4} note="from last month" icon="♙" color="purple"/><Stat title="PRESENT TODAY" value="221" change={2.1} note="89.1% attendance" icon="◷" color="green"/><Stat title="ON LEAVE" value="12" change={-3.2} note="from last week" icon="✈" color="orange"/><Stat title="OPEN SHIFTS" value="7" change={0} note="3 need attention" icon="□" color="pink"/></section><section className="dash-grid"><Attendance/><Requests go={go}/><Schedule go={go}/><Insight go={go}/></section></>}
function Attendance(){return <article className="card attendance"><div className="card-head"><div><h2>Attendance overview</h2><p>Daily attendance across your organization</p></div><select><option>This week</option><option>Last week</option></select></div><div className="chart"><div className="axis"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div>{[82,91,86,94,88,55,38].map((v,i)=><div className="bar" key={i}><i style={{height:v+'%'}}/><small>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</small></div>)}</div><div className="legend"><span>● Present</span><span>● Late</span><span>● Absent</span></div></article>}
function Requests({go}){return <article className="card"><div className="card-head"><div><h2>Leave requests</h2><p>Waiting for your review</p></div><button className="link" onClick={()=>go('Leave')}>View all →</button></div>{[['MC','Maya Chen','Annual leave · Sep 28 – Oct 02','Pending'],['DB','Daniel Brooks','Personal leave · Sep 30','Pending'],['PN','Priya Nair','Sick leave · Sep 24 – Sep 25','Urgent']].map(x=><div className="request" key={x[1]}><b className="avatar">{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span><em className={x[3]}>{x[3]}</em></div>)}<button className="wide" onClick={()=>go('Leave')}>Review all 8 requests</button></article>}
function Schedule({go}){return <article className="card"><div className="card-head"><div><h2>Today's schedule</h2><p>Thursday, September 24</p></div><button className="link" onClick={()=>go('Shifts')}>Full schedule →</button></div>{[['08:00','Morning shift','42 employees'],['12:00','Midday shift','28 employees'],['16:00','Evening shift','36 employees']].map((x,i)=><div className="shift" key={x[0]}><b>{x[0]}</b><i className={'c'+i}/><span><strong>{x[1]}</strong><small>{x[2]}</small></span><em>View</em></div>)}<div className="coverage"><span>Coverage today <b>92%</b></span><i><b/></i><small>7 open positions across 3 shifts</small></div></article>}
function Insight({go}){return <article className="card insight"><span>✦ &nbsp; AI INSIGHT</span><h2>Staffing attention needed</h2><p>Friday's evening shift is projected to be below minimum coverage by 3 employees.</p><button onClick={()=>go('AI Workflows')}>Review recommendation →</button></article>}
function Employees(){const[q,setQ]=useState('');const rows=useMemo(()=>staff.filter(x=>(x.name+x.role+x.dept).toLowerCase().includes(q.toLowerCase())),[q]);return <section className="card page"><div className="card-head"><div><h2>Employee directory</h2><p>248 people across 5 departments</p></div><button className="primary">＋ Add employee</button></div><div className="filters"><label>⌕<input placeholder="Search employees..." value={q} onChange={e=>setQ(e.target.value)}/></label><select><option>All departments</option><option>Engineering</option></select></div><div className="table"><div className="tr th"><span>EMPLOYEE</span><span>DEPARTMENT</span><span>STATUS</span><span>ACTION</span></div>{rows.map(x=><div className="tr" key={x.name}><div className="person"><b className="avatar">{x.initials}</b><span><strong>{x.name}</strong><small>{x.role}</small></span></div><span>{x.dept}</span><span className={'status '+x.status.replace(' ','').toLowerCase()}>● &nbsp;{x.status}</span><button>•••</button></div>)}</div></section>}
function Leave(){const[r,setR]=useState([['Maya Chen','Annual leave','Sep 28 – Oct 02','5 days','Pending'],['Daniel Brooks','Personal leave','Sep 30','1 day','Pending'],['Priya Nair','Sick leave','Sep 24 – Sep 25','2 days','Urgent'],['Liam Wilson','Annual leave','Oct 05 – Oct 07','3 days','Pending']]);const decide=(i,s)=>setR(a=>a.map((x,j)=>i===j?[...x.slice(0,4),s]:x));return <section className="card page"><div className="card-head"><div><h2>Leave review queue</h2><p>Review requests and their coverage impact</p></div><em className="count">{r.filter(x=>['Pending','Urgent'].includes(x[4])).length} awaiting review</em></div><div className="leave-list">{r.map((x,i)=><div className="leave-row" key={x[0]}><b className="avatar">{x[0].split(' ').map(n=>n[0]).join('')}</b><span><strong>{x[0]}</strong><small>{x[1]}</small></span><span><small>DATES</small><strong>{x[2]}</strong></span><span><small>DURATION</small><strong>{x[3]}</strong></span><em className={x[4]}>{x[4]}</em>{['Pending','Urgent'].includes(x[4])?<div><button onClick={()=>decide(i,'Rejected')}>Reject</button><button onClick={()=>decide(i,'Approved')}>Approve</button></div>:<i/>}</div>)}</div></section>}
function AI(){return <section className="workflow"><article className="card"><div className="card-head"><div><small className="eyebrow">WORKFLOW WF-1048</small><h2>Leave impact analysis</h2><p>Maya Chen · Sep 28 – Oct 02</p></div><em className="Pending">Awaiting approval</em></div><div className="steps">{[['✓','Request received','Completed'],['✓','Coverage analysis','Completed'],['✓','Policy validation','Completed'],['4','HR decision','Current']].map((x,i)=><div key={x[1]}><b className={i<3?'done':'current'}>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span></div>)}</div><div className="recommend"><b>✦</b><span><small>AI RECOMMENDATION</small><h3>Approve with coverage adjustment</h3><p>Leave balance and policy checks passed. Assign one open design review to Daniel Brooks to maintain 85% team coverage.</p></span></div><div className="decisions"><button>Request revision</button><button>Reject</button><button className="primary">Approve request</button></div></article><article className="card evidence"><h2>Validation evidence</h2>{[['Leave balance','12 days available'],['Minimum coverage','85% after adjustment'],['Blackout dates','No conflicts'],['Overlapping leave','1 team member']].map((x,i)=><div key={x[0]}><b className={i===3?'warn':''}>✓</b><span><strong>{x[0]}</strong><small>{x[1]}</small></span></div>)}</article></section>}
function Basic({page}){const d={Attendance:['221','Present today','9','Late arrivals','18','Absent'],Shifts:['96%','Morning coverage','84%','Evening coverage','7','Open positions'],Performance:['14','Reviews due','38','Completed','12','Training courses'],Settings:['5','Departments','14','Roles','22','Active managers']}[page];return <><section className="basic-stats">{[0,2,4].map(i=><article className="card" key={i}><small>{d[i+1]}</small><strong>{d[i]}</strong></article>)}</section><article className="card empty"><b>{nav.find(x=>x[0]===page)[1]}</b><h2>{page}</h2><p>This module is ready for your backend integration.</p><button className="primary">Create new</button></article></>}
export default function App(){const[page,setPage]=useState('Dashboard'),[open,setOpen]=useState(false);const content=page==='Dashboard'?<Dashboard go={setPage}/>:page==='Employees'?<Employees/>:page==='Leave'?<Leave/>:page==='AI Workflows'?<AI/>:<Basic page={page}/>;return <div><Sidebar page={page} setPage={setPage} open={open} setOpen={setOpen}/>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}<main><Header page={page} menu={()=>setOpen(true)}/><div className="content">{content}<footer>© 2026 WorkForce360 · Frontend prototype</footer></div></main></div>}
